name: practice
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  animated_text_kit: ^2.0.1
  confetti: ^0.5.2
  datetime_picker_formfield: ^0.1.1
  flutter_spinkit: "^4.1.2"
  flutter_slidable: ^0.5.4
  snappable: ^1.0.1


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - images/

  fonts:
    - family: StardustAdventure          ##give any name you want
      fonts:
        - asset: fonts/StardustAdventure.ttf

